module.exports = [
  // 'https://starwars.fandom.com/wiki/UT-60D_U-wing_starfighter/support_craft',
  // 'https://starwars.fandom.com/wiki/V-wing_airspeeder',
  // 'https://starwars.fandom.com/wiki/VCX-100_light_freighter',
  // 'https://starwars.fandom.com/wiki/YT-2400_light_freighter',
  // 'https://starwars.fandom.com/wiki/Millennium_Falcon',
  // 'https://starwars.fandom.com/wiki/EF76_Nebulon-B_escort_frigate/Legends',
  // 'https://starwars.fandom.com/wiki/MC75_Star_Cruiser',
  // 'https://starwars.fandom.com/wiki/GR-75_medium_transport',
  // 'https://starwars.fandom.com/wiki/Sphyrna-class_Hammerhead_corvette',
  // 'https://starwars.fandom.com/wiki/TIE/sf_space_superiority_fighter',
  // 'https://starwars.fandom.com/wiki/Upsilon-class_command_shuttle',
  // 'https://starwars.fandom.com/wiki/AAL-1971/9.1_Troop_Transport',
  // 'https://starwars.fandom.com/wiki/Oevvaor_jet_catamaran',
  // 'https://starwars.fandom.com/wiki/TIE/LN_starfighter',
  // 'https://starwars.fandom.com/wiki/TIE_Advanced_x1',
  // 'https://starwars.fandom.com/wiki/TIE/sa_bomber/Legends',
  // 'https://starwars.fandom.com/wiki/TIE/D_Defender',
  // 'https://starwars.fandom.com/wiki/TIE/sk_x1_experimental_air_superiority_fighter',
  // 'https://starwars.fandom.com/wiki/TIE/IN_interceptor/Legends',
  // 'https://starwars.fandom.com/wiki/Delta-class_JV-7_escort_shuttle',
  // 'https://starwars.fandom.com/wiki/Delta-class_T-3c_shuttle',
  // 'https://starwars.fandom.com/wiki/Zeta-class_Heavy_Cargo_Shuttle',
  // 'https://starwars.fandom.com/wiki/Imperial_II-class_Star_Destroyer/Legends',
  // 'https://starwars.fandom.com/wiki/Gladiator-class_Star_Destroyer/Legends',
  // 'https://starwars.fandom.com/wiki/Imperial_I-class_Star_Destroyer/Legends',
  // 'https://starwars.fandom.com/wiki/Imperial_II-class_Star_Destroyer/Legends',
  // 'https://starwars.fandom.com/wiki/Interdictor-class_Star_Destroyer/Legends',
  // 'https://starwars.fandom.com/wiki/Nebula-class_Star_Destroyer',
  // 'https://starwars.fandom.com/wiki/Pellaeon-class_Star_Destroyer',
  // 'https://starwars.fandom.com/wiki/Providence-class_carrier/destroyer',
  // 'https://starwars.fandom.com/wiki/Republic-class_Star_Destroyer',
  // 'https://starwars.fandom.com/wiki/Victory_I-class_Star_Destroyer',
  // 'https://starwars.fandom.com/wiki/DS-1_Death_Star_Mobile_Battle_Station',
  // 'https://starwars.fandom.com/wiki/Death_Star_II/Legends',
  // 'https://starwars.fandom.com/wiki/Sun_Crusher',
  // 'https://starwars.fandom.com/wiki/74-Z_speeder_bike/Legends',
  // 'https://starwars.fandom.com/wiki/BARC_speeder',
  // 'https://starwars.fandom.com/wiki/All_Terrain_Armored_Transport/Legends',
  // 'https://starwars.fandom.com/wiki/All_Terrain_Armored_Cargo_Transport',
  // 'https://starwars.fandom.com/wiki/All_Terrain_Scout_Transport',
  // 'https://starwars.fandom.com/wiki/All_Terrain_Scout_Transport/Legends',
  // 'https://starwars.fandom.com/wiki/HAVw_A6_Juggernaut/Legends',
  // 'https://starwars.fandom.com/wiki/TX-225_GAVw_%22Occupier%22_combat_assault_tank',
  // 'https://starwars.fandom.com/wiki/TX-225_GAVr_%22Occupier%22_combat_assault_tank',
  // 'https://starwars.fandom.com/wiki/N-1_starfighter/Legends',
  // 'https://starwars.fandom.com/wiki/Aggressive_ReConnaissance-170_starfighter/Legends',
  // 'https://starwars.fandom.com/wiki/CR90_corvette/Legends',
  // 'https://starwars.fandom.com/wiki/J-type_327_Nubian_starship',
  // 'https://starwars.fandom.com/wiki/J-type_star_skiff',


  'https://starwars.fandom.com/wiki/H-type_Nubian_yacht/Legends',
  'https://starwars.fandom.com/wiki/Low_Altitude_Assault_Transport/infantry/Legends',
  'https://starwars.fandom.com/wiki/Venator-class_Star_Destroyer/Legends',
  'https://starwars.fandom.com/wiki/All_Terrain_Tactical_Enforcer/Legends',
  'https://starwars.fandom.com/wiki/Lucrehulk-class_battleship',
  'https://starwars.fandom.com/wiki/C-9979_landing_craft/Legends',
  'https://starwars.fandom.com/wiki/Subjugator-class_heavy_cruiser',
  'https://starwars.fandom.com/wiki/Armored_Assault_Tank',
  'https://starwars.fandom.com/wiki/Multi-Troop_Transport/Legends',
  'https://starwars.fandom.com/wiki/Tsmeu-6_personal_wheel_bike',
  'https://starwars.fandom.com/wiki/Single_Trooper_Aerial_Platform',
  'https://starwars.fandom.com/wiki/MC85_Star_Cruiser',
  'https://starwars.fandom.com/wiki/Resistance_transport_pod',
  'https://starwars.fandom.com/wiki/Eta-2_Actis-class_light_interceptor',
  'https://starwars.fandom.com/wiki/Red_Five_(X-wing_starfighter)',
  'https://starwars.fandom.com/wiki/Soulless_One',
  'https://starwars.fandom.com/wiki/Aayla_Secura%27s_Eta-2_Actis-class_light_interceptor',
  'https://starwars.fandom.com/wiki/Sharp_Spiral',
  'https://starwars.fandom.com/wiki/Anakin_Skywalker%27s_red_Delta-7_Aethersprite-class_light_interceptor',
  'https://starwars.fandom.com/wiki/Obi-Wan_Kenobi%27s_Eta-2_Actis-class_light_interceptor',
  'https://starwars.fandom.com/wiki/Yoda%27s_Jedi_interceptor',
  'https://starwars.fandom.com/wiki/Ebon_Hawk',
  'https://starwars.fandom.com/wiki/Twilight',
  'https://starwars.fandom.com/wiki/Jabitha',
  'https://starwars.fandom.com/wiki/Chu%27unthor',
  'https://starwars.fandom.com/wiki/Another_Chance',
  'https://starwars.fandom.com/wiki/Tantive_IV/Legends',
  'https://starwars.fandom.com/wiki/Anodyne_(Nebulon-C)',
  'https://starwars.fandom.com/wiki/L%27ulo_L%27ampar%27s_A-wing',
  'https://starwars.fandom.com/wiki/T-70_X-wing_starfighter',
  'https://starwars.fandom.com/wiki/Ninka',
  'https://starwars.fandom.com/wiki/Cobalt_Hammer',
  'https://starwars.fandom.com/wiki/Raddus_(MC85_Star_Cruiser)',
  'https://starwars.fandom.com/wiki/Cobalt_Wasp',
  'https://starwars.fandom.com/wiki/Crimson_Bolide',
  'https://starwars.fandom.com/wiki/Crimson_Hailstorm',
  'https://starwars.fandom.com/wiki/Crimson_Cutter',
  'https://starwars.fandom.com/wiki/Tallissan_Lintra%27s_RZ-2_A-wing_interceptor',
  'https://starwars.fandom.com/wiki/Fortitude_(transport)',
  'https://starwars.fandom.com/wiki/Vigil',
  'https://starwars.fandom.com/wiki/Unidentified_YV-865_Aurore-class_freighter',
  'https://starwars.fandom.com/wiki/Jaster%27s_Legacy',
  'https://starwars.fandom.com/wiki/Nightbrother_(Gauntlet_fighter)',
  'https://starwars.fandom.com/wiki/Gauntlet_(Pre_Vizsla)/Legends',
  'https://starwars.fandom.com/wiki/Slave_I/Legends',
  'https://starwars.fandom.com/wiki/Barsen%27thor%27s_Defender-class_light_corvette',
  'https://starwars.fandom.com/wiki/Nebulon_Ranger',
  'https://starwars.fandom.com/wiki/Chu%27unthor',
  'https://starwars.fandom.com/wiki/Hero_of_Tython%27s_Defender-class_light_corvette',
  'https://starwars.fandom.com/wiki/Spirit_of_Corellia',
  'https://starwars.fandom.com/wiki/SunGem',
  'https://starwars.fandom.com/wiki/Whitecloak_fighter',
]